# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usid', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('latStart', models.FloatField()),
                ('longStart', models.FloatField()),
                ('latEnd', models.FloatField()),
                ('longEnd', models.FloatField()),
                ('thickness', models.FloatField()),
                ('color', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
