# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_auto_20161103_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usid', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=100)),
                ('latStart', models.FloatField()),
                ('longStart', models.FloatField()),
                ('latEnd', models.FloatField()),
                ('longEnd', models.FloatField()),
                ('thickness', models.FloatField()),
                ('color', models.FloatField()),
                ('timestamp', models.IntegerField(blank=True)),
            ],
        ),
    ]
