# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='longEnd',
            new_name='lonEnd',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='longStart',
            new_name='lonStart',
        ),
    ]
