# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_auto_20161104_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='latEnd',
            new_name='latend',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='latStart',
            new_name='latstart',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='lonEnd',
            new_name='lonend',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='lonStart',
            new_name='lonstart',
        ),
    ]
